
# Code Highlight theme
# Available value:
#    normal | night | night yilia | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
# night yilia - https://github.com/litten/hexo-theme-yilia
highlight_theme: night

# Sidebar settings 侧边栏头像设置
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "Study, Study, Study  ..."
sidebar-avatar: images/head.png      # use absolute URL, seeing it's used in both `/` and `/about/`
# 侧边栏小部件显示
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
- category

# SNS settings 底部links和头像下links设置
# RSS: false
weibo_username:     onepiece666
# zhihu_username:     Demonbane
github_username:    wkk1994
# twitter_username:   Demonbane_x
#facebook_username:  wkk1994
#linkedin_username:  wkk1994

## Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 10              # A tag will be featured if the size of it is more than this condition value

# Site settings
SEOTitle: wkk1994
email: beantech@gmail.com
description: ""
keyword: ""
header-img: images/home.jpg
signature: false #show signature 签名设置
signature-img: img/signature/BeanTechSign-white.png 

# Analytics settings 统计设置
# Baidu Analytics
ba_track_id: 8e2cdaa26ea70e7fedbdbafd3c8d9c84
# Google Analytics
#ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
#ga_domain: yoursite

# Show number of visitors to each article. 阅读数配置
# You can visit https://leancloud.cn to get AppID and AppKey.
leancloud_visitors:
  enable: true
  app_id: 6eLbTrCEFzVG3fC34POHg4i0-gzGzoHsz #<app_id>
  app_key: m81IH9iicdwjYMLcH62Dm6q3 #<app_key>
  betterPerformance: true
valine:
  enable: false
  visitor: false # 文章访问量统计

share_share: # share分享
  enable: true

livere_uid: MTAyMC80NDI5Ny8yMDgyOQ== #来比力评论
home_posts_tag: true #首页显示标签
baidusitemap:
  autoPush: true #百度自动推送